"use client";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import localFont from "next/font/local";
import "./globals.css";
import { Provider } from 'react-redux';
import store from '@/store/store';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider store={store}>
         <AppRouterCacheProvider>
        {children}
         </AppRouterCacheProvider>
        </Provider>
      </body>
    </html>
  );
}
